/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceCategory = IDL.Variant({
  'ac' : IDL.Null,
  'oil' : IDL.Null,
  'tires' : IDL.Null,
  'brakes' : IDL.Null,
  'accessories' : IDL.Null,
  'body' : IDL.Null,
  'wash' : IDL.Null,
  'insurance' : IDL.Null,
  'suspension' : IDL.Null,
  'engine' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'carModel' : IDL.Text,
  'date' : Time,
  'name' : IDL.Text,
  'user' : IDL.Principal,
  'serviceId' : IDL.Nat,
  'phone' : IDL.Text,
});
export const T = IDL.Record({
  'cancelled' : IDL.Nat,
  'pending' : IDL.Nat,
  'completed' : IDL.Nat,
  'confirmed' : IDL.Nat,
});
export const Membership = IDL.Record({
  'activated' : IDL.Bool,
  'endDate' : Time,
  'user' : IDL.Principal,
  'activationDate' : Time,
  'remainingCarWashes' : IDL.Nat,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : ServiceCategory,
  'price' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CarWashStats = IDL.Record({
  'avgCarWashesPerMember' : IDL.Float64,
  'totalCarWashesUsed' : IDL.Nat,
  'totalMembers' : IDL.Nat,
  'activeMembers' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addService' : IDL.Func(
      [IDL.Text, ServiceCategory, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Nat],
      [Booking],
      [],
    ),
  'countBookingsByStatus' : IDL.Func([], [T], ['query']),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllMembers' : IDL.Func([], [IDL.Vec(Membership)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getBookingsByStatus' : IDL.Func(
      [BookingStatus],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getCallerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCarWashStats' : IDL.Func([], [CarWashStats], ['query']),
  'getMembership' : IDL.Func([IDL.Principal], [Membership], ['query']),
  'getServicesByCategory' : IDL.Func(
      [ServiceCategory],
      [IDL.Vec(Service)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'purchaseMembership' : IDL.Func([], [Membership], []),
  'redeemCarWash' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceCategory = IDL.Variant({
    'ac' : IDL.Null,
    'oil' : IDL.Null,
    'tires' : IDL.Null,
    'brakes' : IDL.Null,
    'accessories' : IDL.Null,
    'body' : IDL.Null,
    'wash' : IDL.Null,
    'insurance' : IDL.Null,
    'suspension' : IDL.Null,
    'engine' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'carModel' : IDL.Text,
    'date' : Time,
    'name' : IDL.Text,
    'user' : IDL.Principal,
    'serviceId' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const T = IDL.Record({
    'cancelled' : IDL.Nat,
    'pending' : IDL.Nat,
    'completed' : IDL.Nat,
    'confirmed' : IDL.Nat,
  });
  const Membership = IDL.Record({
    'activated' : IDL.Bool,
    'endDate' : Time,
    'user' : IDL.Principal,
    'activationDate' : Time,
    'remainingCarWashes' : IDL.Nat,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : ServiceCategory,
    'price' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CarWashStats = IDL.Record({
    'avgCarWashesPerMember' : IDL.Float64,
    'totalCarWashesUsed' : IDL.Nat,
    'totalMembers' : IDL.Nat,
    'activeMembers' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addService' : IDL.Func(
        [IDL.Text, ServiceCategory, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Time, IDL.Nat],
        [Booking],
        [],
      ),
    'countBookingsByStatus' : IDL.Func([], [T], ['query']),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllMembers' : IDL.Func([], [IDL.Vec(Membership)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getBookingsByStatus' : IDL.Func(
        [BookingStatus],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCarWashStats' : IDL.Func([], [CarWashStats], ['query']),
    'getMembership' : IDL.Func([IDL.Principal], [Membership], ['query']),
    'getServicesByCategory' : IDL.Func(
        [ServiceCategory],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'purchaseMembership' : IDL.Func([], [Membership], []),
    'redeemCarWash' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };