/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'carModel' : string,
  'date' : Time,
  'name' : string,
  'user' : Principal,
  'serviceId' : bigint,
  'phone' : string,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface CarWashStats {
  'avgCarWashesPerMember' : number,
  'totalCarWashesUsed' : bigint,
  'totalMembers' : bigint,
  'activeMembers' : bigint,
}
export interface Membership {
  'activated' : boolean,
  'endDate' : Time,
  'user' : Principal,
  'activationDate' : Time,
  'remainingCarWashes' : bigint,
}
export interface Service {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'category' : ServiceCategory,
  'price' : bigint,
}
export type ServiceCategory = { 'ac' : null } |
  { 'oil' : null } |
  { 'tires' : null } |
  { 'brakes' : null } |
  { 'accessories' : null } |
  { 'body' : null } |
  { 'wash' : null } |
  { 'insurance' : null } |
  { 'suspension' : null } |
  { 'engine' : null };
export interface T {
  'cancelled' : bigint,
  'pending' : bigint,
  'completed' : bigint,
  'confirmed' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addService' : ActorMethod<
    [string, ServiceCategory, string, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookService' : ActorMethod<[string, string, string, Time, bigint], Booking>,
  'countBookingsByStatus' : ActorMethod<[], T>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllMembers' : ActorMethod<[], Array<Membership>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getBookingsByStatus' : ActorMethod<[BookingStatus], Array<Booking>>,
  'getCallerBookings' : ActorMethod<[], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCarWashStats' : ActorMethod<[], CarWashStats>,
  'getMembership' : ActorMethod<[Principal], Membership>,
  'getServicesByCategory' : ActorMethod<[ServiceCategory], Array<Service>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'purchaseMembership' : ActorMethod<[], Membership>,
  'redeemCarWash' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];